### ISSUE TITLE
Error: too many arguments 

### ISSUE THREAD

**Issue by parseb** [St4rgarden/RiteOfMoloch#7]
On: `npx hardhat test`
Returns:
```
 1) Rite of Moloch Contract
       "before all" hook in "Rite of Moloch Contract":
     Error: too many arguments:  in Contract constructor (count=4, expectedCount=0, code=UNEXPECTED_ARGUMENT, version=contracts/5.5.0)
```

Likely Cause:
RiteOfMoloch constructor takes no argument 

https://github.com/St4rgarden/RiteOfMoloch/blob/2c12cce8b1f518cb8875a7b33228de16e57fec0f/contracts/RiteOfMoloch.sol#L98-L100

yet 4 provided in test initialization.

https://github.com/St4rgarden/RiteOfMoloch/blob/2c12cce8b1f518cb8875a7b33228de16e57fec0f/test/RiteOfMolochTests.js#L99-L104

**Comment by St4rgarden** [comment]
All tests are broken because this repo was deprecated prior to the cohort.  The repo where we moved development activity is a pretty advanced repo utilizing typescript bindings and our custom developer toolkit called Quiver.

This is an issue using the old contract's constructor parameters.  The contract no longer has a constructor and now relies on being initialized.  The raw contract is deployed as an implementation contract which can be targeted by minimal proxies.  This allows the proxies to deploy virtually zero code; and still use the comprehensive logic contained in the implementation contract.  More info: https://docs.openzeppelin.com/contracts/4.x/api/proxy

In order to fix this issue we would need a fully updated test suite; incorporating the RiteOfMoloch factory.

**Comment by parseb** [comment]
to be solved in cohort repo
